### ISSUE TITLE
Website Dates - PHP : DC122617 (Katherine)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1119]
![image](https://cloud.githubusercontent.com/assets/10079829/14898317/23965430-0d54-11e6-8e55-8865ea05aa21.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
hi Brad, it is still showing **,17** it should show **,18**
http://pilgrimages.com/frcalloway/holyland-december

**Comment by bradatkins** [comment]
Fixed
