### ISSUE TITLE
421456- DC081516 - pax cxld but showing on invoice/recap still

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1262]
![image](https://cloud.githubusercontent.com/assets/8440903/16496951/942ac1e6-3ec2-11e6-848f-eaf5e1c45cbd.png)

![image](https://cloud.githubusercontent.com/assets/8440903/16496954/9b50f6d4-3ec2-11e6-8bc7-1f7ffa83af3e.png)

![image](https://cloud.githubusercontent.com/assets/8440903/16496967/a47c6a2c-3ec2-11e6-8a7d-da2e6b748f45.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
She's still showing on the invoice:

![image](https://cloud.githubusercontent.com/assets/8440903/17973506/b8c1148c-6ab0-11e6-83d8-7ded8146e8ba.png)

**Comment by bradatkins** [comment]
Fixed
