### ISSUE TITLE
DB  not searching correctly

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#130]
![searching](https://cloud.githubusercontent.com/assets/8440903/5573305/bf87f930-8f78-11e4-837c-4664066d4232.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
Now nothing is showing up when searching by the tour and date:

![image](https://cloud.githubusercontent.com/assets/8440903/5704164/caba1026-9a3c-11e4-81b3-b346d19b3103.png)


Also, searching from March to July changes my search to march to march:

![image](https://cloud.githubusercontent.com/assets/8440903/5704172/e0de45fc-9a3c-11e4-88b4-d91559fcd87e.png)

**Comment by bradatkins** [comment]
Fixed 

![image](https://cloud.githubusercontent.com/assets/8440255/7102348/4a447df0-e04b-11e4-8091-20db40cafa28.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7102361/2fe8f660-e04c-11e4-81ce-49145bf589df.png)

**Comment by ali206** [comment]
Still not working for me:

![image](https://cloud.githubusercontent.com/assets/8440903/7139588/27a4664c-e295-11e4-837e-674f3d9d91c0.png)


![image](https://cloud.githubusercontent.com/assets/8440903/7139604/2e21abb0-e295-11e4-88d5-73d16303b562.png)
