### ISSUE TITLE
ARC TICKETS -- Trying to search by issue date and i get a blank page

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1325]
![image](https://cloud.githubusercontent.com/assets/8440903/17038510/0938975e-4f64-11e6-9b1a-ac816589c330.png)

![image](https://cloud.githubusercontent.com/assets/8440903/17038522/129c30da-4f64-11e6-8f8c-72c3a6d870ce.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
Still not working, and I can't search by ticket #:

![image](https://cloud.githubusercontent.com/assets/8440903/17113629/869b421a-5279-11e6-8e80-20b9ef059f9a.png)
