### ISSUE TITLE
ARC tickets to be sorted by ticket #

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1434]
currently it looks like they're sorted by booking # but ticket # is much easier to look at

![image](https://cloud.githubusercontent.com/assets/8440903/17908125/21131680-694d-11e6-859c-b9f46518c924.png)

**Comment by bradatkins** [comment]
Done

**Comment by ali206** [comment]
Don't kill me, i should've been more specific. 

They should be sorted by ticket # based on issue date, so all tickets issued for 8/22/16 should be in numerical order.

**Comment by bradatkins** [comment]
Done

**Comment by ali206** [comment]
Tickets should still show low to high though, 803 should be on top:

![image](https://cloud.githubusercontent.com/assets/8440903/17974613/c4916f38-6ab4-11e6-9bf2-1fdc13ab6409.png)

**Comment by bradatkins** [comment]
Done, anything else? :)

**Comment by ali206** [comment]
Thank you :)
