### ISSUE TITLE
423938 - ticket not showing on recap but seems like it's in DB

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#1459]
for Reynerio:

![image](https://cloud.githubusercontent.com/assets/8440903/18146458/b478bf46-6f9d-11e6-8836-1d06252408dc.png)

![image](https://cloud.githubusercontent.com/assets/8440903/18146462/c18a1702-6f9d-11e6-80f0-b529590fc256.png)

**Comment by bradatkins** [comment]
Fixed. Passenger Reynerio had a space at the end of their name which was causing a mismatch

**Comment by ali206** [comment]
$ amt still not showing on recap

![image](https://cloud.githubusercontent.com/assets/8440903/18849253/19408e60-8400-11e6-82cb-0cce4d71e2dd.png)
