### ISSUE TITLE
GLITCH: DB Not Compiling Group Flight Itineraries to Zip - Just hanging there on blank page (chris)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1472]
9bd0e33f784deb2374f3ed4f894a7984

![image](https://cloud.githubusercontent.com/assets/10079829/18447342/325b649a-78f4-11e6-9d37-9c78e87fae1b.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
Still not working

It now compiles BUT as .html files
I cannot print them all at once
Even if I try to print them one at a time or open the file, it takes me to a website that is no longer found.

![image](https://cloud.githubusercontent.com/assets/10079829/18481963/5140e534-79ac-11e6-8d9a-ce9503336615.png)

**Comment by bradatkins** [comment]
It opens fine in IE.

Not sure what it's expected to be other then an .html file

**Comment by chris206** [comment]
It now:
compiles to zip file - great
xip file is filled with each flight itinerary - great
after extracting them, clicking any of them brings you to a dead website with no information. - no good

The issue is that we need to be able to drag and drop all files at once into the printer dialog box.
Right now, this is not possible either because the files are broken OR because we cant print multiples webpages at once.

**Comment by chris206** [comment]
Hi Brad - any word on this? I'm still printing them one by one

**Comment by bradatkins** [comment]
This isn't a DB thing. Your computer thinks the file isn't there. Try opening it in IE or someone elses computer

**Comment by chris206** [comment]
I opened on IE and it worked - I could drag and drop. They didnt open up on chrome on other computers.

I dragged all and then dropped them - and that works. Unfortunatelty, I received a prompt to print each of the 38 itineraries which was - but it still saved me considerable time.

In the office, 90% of us use Chrome. I've changed my default program for html-files to IE, but it would be ideal if this worked on chrome so that other users were more likely to use the feature successfully.
