### ISSUE TITLE
417225 - math is all wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#152]
This booking has 11 registered pax and no one has a subtotal or total tour amount so it looks like they don't owe us any money. 

Can you please fix this? Updating wasn't doing anything.

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417225&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
OK it's something to do with the changes for the SD discount. I'll check

**Comment by bradatkins** [comment]
Actually it turns out this is the first time that an SD discount has had to be applied to an order with more then 1 PAX. I have to figure this out.

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
The Math still isn't correct:

Order total should be $46,861 with the inclusion of travel insurance - $4769 SD Discount = $42,092 balance due.

**Comment by bradatkins** [comment]
I'm a little confused by your math....

9 PAX at 3,880 = 34,920
2 PAX at 4,769 = 9,538

$44,458 - 4,769 = 39,689 not $42,092

Am I doing something wrong there?

**Comment by ali206** [comment]
i'm an idiot sorry, i was adding in insurance sep. 

this is correct, thanks!
