### ISSUE TITLE
Multiple insurances

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#156]
This to me means having both premiums show correctly in the DB which as far as i know has been working correctly other than for FREE's and SD discounts. 

What i mean by that is that when free's or SD discounts are applied, the insurance premium should automatically adjust to $108, not TG pricing of $103.00.

It's never done that correctly so we've been declining insurance and manually adding the correct premium of $108.

**Comment by bradatkins** [comment]
I believe this is fixed. This portion of the code wasn't looking at "Active only" insurance premiums. Please check and let me know

**Comment by ali206** [comment]
Not fixed - 417949 i just accepted the ins. for this SD and it shows as $103

![image](https://cloud.githubusercontent.com/assets/8440903/6026394/7c494240-aba8-11e4-992a-8b8429cc31b7.png)

**Comment by bradatkins** [comment]
OK I think it's fixed for real this time. I hope

**Comment by ali206** [comment]
I just created a booking under your name as a Fr. and the SD discount didn't automatically apply so i typed SD in as a promo which updated the invoice and showed the correct balance due of $108.00 but it didn't actually change the insurance premium on the invoice.  It's still showing as $230:

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=417981&GENERATED=TRUE&SHOW_COMMISSION=Y

**Comment by bradatkins** [comment]
Closing, hasn't happened again since
