### ISSUE TITLE
Add to Github: In Addition - "Title" (patrick)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1629]
![image](https://cloud.githubusercontent.com/assets/10079829/20072608/0b7fbf04-a4f7-11e6-9165-bb9edb2d6fcf.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
i ran a test and i still can't make the selection:

![image](https://cloud.githubusercontent.com/assets/10079829/20891751/b1f384fe-bad9-11e6-803d-df4bf48c98d9.png)
