### ISSUE TITLE
#425903-Refund in AUD

### ISSUE THREAD

**Issue by Irena206** [206Tours/DB#1635]
Hi Brad ,
Can you please apply AUD refund to show as  948.44 instead of "0".
thanks, 

![image](https://cloud.githubusercontent.com/assets/14838466/20119314/0ca6db76-a5d6-11e6-9061-4a0f01551a26.png)

**Comment by bradatkins** [comment]
Done

**Comment by Irena206** [comment]
Customer side still incorrect ! refund amount should show as"1,896.88" 


![image](https://cloud.githubusercontent.com/assets/14838466/20217987/7dbeaac0-a7f0-11e6-91d6-5d6903b80ccd.png)

**Comment by bradatkins** [comment]
Forgot the minus sign. Check now

**Comment by Irena206** [comment]
Perfect, Thank you.
