### ISSUE TITLE
Registration - Can't clear radio options

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#1668]
not sure if it is you or BD but can you please look into this issue. i tested tour 1 these is no session id.

![image](https://cloud.githubusercontent.com/assets/10079829/20538375/dfd3acca-b0be-11e6-9564-6cdbe755b982.png)

**Comment by bradatkins** [comment]
That's me. I'll check it as well as the checkbox and radio button right
beside each other

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
i just checked tour 1 again and i still cant clear options:

![image](https://cloud.githubusercontent.com/assets/10079829/20891013/0d128f86-bad7-11e6-8edd-4b5c9331bf0b.png)

**Comment by chris206** [comment]
I've spoken with Melissa,

On subsequent emails, can we just have it say "Your Order Comments" instead of "Dear Maggie Marito"?

As of right now, it says "Dear Maggie Marito," and is then followed by her comments and nothing else. It looks strange

**Comment by bradatkins** [comment]
Sorry? Not sure what this has to do with clearing radio options?

**Comment by chris206** [comment]
mistake - deleted
