### ISSUE TITLE
DB is attempting to overwrite passenger 1 info multiple times, instead of adding passenger 2, 3, 4, etc

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1687]
![image](https://cloud.githubusercontent.com/assets/22382144/20801020/86ab3be2-b7b5-11e6-9207-7480e165b193.png)

**Comment by chris206** [comment]
![image](https://cloud.githubusercontent.com/assets/22382144/20803150/39ca0c2a-b7bc-11e6-9589-81235f206dca.png)

Here is a broken order, I cant even add a second passenger in add passenger

![image](https://cloud.githubusercontent.com/assets/22382144/20803183/527537ae-b7bc-11e6-9c25-2494e50dd4af.png)

**Comment by bradatkins** [comment]
I've fixed her order, but I'm keeping this issue open so I can fix root cause

**Comment by chris206** [comment]
Caterina provided another example 424837 (Caterina) #1695

**Comment by chris206** [comment]
Sammie provided another example (but corrected it manually before completing)
It seems to be automatically checking the "same as contact info box"

![image](https://cloud.githubusercontent.com/assets/22382144/21273285/d3ec3d16-c390-11e6-9ad3-9e2e2e51613f.png)

**Comment by bradatkins** [comment]
This should be fixed now

**Comment by chris206** [comment]
Passenger number has been re-named, unfortunately the main issue is still unresolved.
