### ISSUE TITLE
423947 - DB overwriting correct wife info with duplicate husband info

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1723]
Client info was overwritten on 10/17. 
system overwrote all of the wife's info with duplicate husband info. Let no trace of name change.

Please use original invoice for correct client info

Husband's passport: 443314167 EXP: Jun 2 2018
Wife's passport: 442461350 EXP: Apr 15 2018

![image](https://cloud.githubusercontent.com/assets/22382144/21112135/9276b45e-c072-11e6-8710-4071f8fd5250.png)

![image](https://cloud.githubusercontent.com/assets/22382144/21112110/76a166e8-c072-11e6-943a-64d7abaa06db.png)

**Comment by bradatkins** [comment]
That's really strange. I've fixed the order and will look into why.

**Comment by chris206** [comment]
This is still happening with every order that includes people with prior info. (most of our orders)

Our best clients - those booking more that 1 passenger - will be really frustrated by it.
All users are really frustrated with it.

**Comment by bradatkins** [comment]
Can you email me a new IDE example please.

**Comment by bradatkins** [comment]
For now I've disabled the ability to select more than 1 PAX (you'll have to use the "Add New Passenger" button. 

Try that out and let me know

**Comment by chris206** [comment]
ok, Sandy was asking what is the ETA for the return of the feature.

Should this fix the drop down issue?

**Comment by bradatkins** [comment]
Yes it should fix the drop down issue.

No ETA yet, and really no impact as you can continue to add multiple
passengers, you just have to click the add passenger button.

**Comment by chris206** [comment]
as long as no change for clients - no problem.

**Comment by bradatkins** [comment]
Nope, this is only a change for 206 Tours Staff.

**Comment by chris206** [comment]
it fixes 85% of the problem.

Adding p1 in drop down is working,

Adding the p2 fails to remember the country of p2 passport issuance
AND overwritesthe p1 gender?
