### ISSUE TITLE
Wyoming is Missing from US States (Liz)

### ISSUE THREAD

**Issue by chris206** [206Tours/DB#1855]
Wyoming isnt listed during registration, but does appear when we go back in.
Apparently, there are 60,000 Catholics in the Diocese of Cheyenne

![image](https://cloud.githubusercontent.com/assets/22382144/22569415/72063cc8-e965-11e6-974a-5b8e76cf87db.png)

**Comment by chris206** [comment]
![image](https://cloud.githubusercontent.com/assets/22382144/22570615/36dadc4e-e96a-11e6-8789-f2cd72db192a.png)

**Comment by bradatkins** [comment]
Fixed

**Comment by chris206** [comment]
It isnt fixed yet. When I change account to Wyoming, it all looks good, but when I shopping cart the order - it defaults to Alaska because there is no option for Wyoming

All looks goof in Accounts
![image](https://cloud.githubusercontent.com/assets/22382144/22595130/244144e4-e9f4-11e6-991a-8d7f6e2bb361.png)

So I press shopping cart and find the tour.... but it has defaulted to Alaska because Wyoming isnt in the table

![image](https://cloud.githubusercontent.com/assets/22382144/22595178/49e9fa10-e9f4-11e6-9944-31104968dd25.png)

![image](https://cloud.githubusercontent.com/assets/22382144/22595189/54c3194e-e9f4-11e6-97f1-974d862f7898.png)


Why are we pulling State info from more than one table? 3 tables?

**Comment by chris206** [comment]
any word on this?

**Comment by bradatkins** [comment]
Fixed
