### ISSUE TITLE
adding passenger

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#552]
Hi Brad,

When i try to add a new passenger to the Hahn order the box comes up, i put the number of passengers i want to add in the box, click ok and the box keep coming back. It wont go away! i cant even close out of the browser. Then finally after clicking OK and cxl about 20 times it takes me to a completely different reservation with the same last name just not at all the same people or tour.

![image](https://cloud.githubusercontent.com/assets/8440601/9477065/3aa2d406-4b3e-11e5-8e8d-1e0f3a849544.png)

**Comment by bradatkins** [comment]
Hmm odd. Does the same thing happen for anyone else?

**Comment by Sandra206** [comment]
Yes Yaritza tried as well and the same exact thing happened.


________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold
Director of Operations
206 Tours Inc.
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687  |  631.361.4644  ext. 104  |  Fax: 631.361.3682
sandra@206Tours.com<mailto:sandra@206tours.com>   |  Skype: sandra.savic.lippold

[http://www.206tours.com/sigs/facebook.png]<https://www.facebook.com/206tours>  [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>

**Comment by bradatkins** [comment]
ok I see the issue. I'm figuring it out now

**Comment by bradatkins** [comment]
Fixed

**Comment by Sandra206** [comment]
Hi Brad,

I tested this and its still not working =(



________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold
Director of Operations
206 Tours Inc.
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687  |  631.361.4644  ext. 104  |  Fax: 631.361.3682
sandra@206Tours.com<mailto:sandra@206tours.com>   |  Skype: sandra.savic.lippold

[http://www.206tours.com/sigs/facebook.png]<https://www.facebook.com/206tours>  [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>

**Comment by bradatkins** [comment]
Is it still doing the multiple prompts?

**Comment by Sandra206** [comment]
It works in Chrome but in Safari its not giving multiple prompts but after the prompt nothing happens.


________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Sandra Lippold
Director of Operations
206 Tours Inc.
206Tours.com<http://www.206tours.com/>

Tel: 800.206.8687  |  631.361.4644  ext. 104  |  Fax: 631.361.3682
sandra@206Tours.com<mailto:sandra@206tours.com>   |  Skype: sandra.savic.lippold

[http://www.206tours.com/sigs/facebook.png]<https://www.facebook.com/206tours>  [http://www.206tours.com/sigs/twitter.png] <https://twitter.com/thenew206Tours>   [http://www.206tours.com/sigs/pintrest.png] <https://www.pinterest.com/206Tours>   client letters<https://www.206tours.com/letters/index.htm>

**Comment by bradatkins** [comment]
Hmmm. I don't have Safari so not sure I'll be able to test. I'll look but I
don't really support Safari.

Brad
