### ISSUE TITLE
marking passengers as canceled in order status

### ISSUE THREAD

**Issue by Sandra206** [206Tours/DB#624]
Hi Brad,
we need everyone to be able to change the order status to canceled. Is it possible to make this option for everyone not only admin?

![image](https://cloud.githubusercontent.com/assets/8440601/11274319/30dd1c0a-8ea6-11e5-9394-6e25440b89c1.png)

**Comment by bradatkins** [comment]
Done

**Comment by Sandra206** [comment]
Brad this is still not working as not all Users are able to set their clients as "cancelled"
