### ISSUE TITLE
421464 - cc charge issue

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#639]
$400 CAD was charged but when you look at invoice in USD charge amount does not change? ( I don't remember if it's supposed to but i would assume it would)

and for some reason the charge is showing in current batches, not settled batches even though it was charged yesterday.  But it still posted in the DB as 11/30?

https://www.206tours.com/register/copysource/invoice_pdf.php?OrderID=421464&TravelerID=28449&GENERATED=TRUE&SHOW_COMMISSION=Y&SHOW_CUS_CURRENCY=N

**Comment by bradatkins** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/8440255/13590004/5927d5e2-e4aa-11e5-886f-c8e3ca847c48.png)

**Comment by ali206** [comment]
This is not fixed still - converting the wrong way like all the others i swear i'm not crazy i've asked other people to make sure I was correct.


CAD $3048 was charged but is showing as below in CAD invoice...the $400 payment is incorrect still as well.

![image](https://cloud.githubusercontent.com/assets/8440903/14086817/1f674da0-f4f5-11e5-9ecf-98569f0b2185.png)

![image](https://cloud.githubusercontent.com/assets/8440903/14086801/0d2e9e18-f4f5-11e5-9b63-99db73c46772.png)

**Comment by bradatkins** [comment]
Please call Elavon and validate. As it's my understanding that that 3048 is
USD, they are just identifying that the original currency was CAD.

The whole setup they have is confusing, and I could be wrong, but...

**Comment by ali206** [comment]
Just called them and she confirmed what i've been telling you. 

In MC account, the currency such as CAD is letting us know that the amount of $3048 was charged in CAD dollars to our account, NOT USD.  Only shows as USD in our bank account once posted.

**Comment by bradatkins** [comment]
OK I've made the change, let me know next time a non-USD charge goes through

**Comment by ali206** [comment]
Ok so do i have to fix the bookings with charges on them already or do you still? I just tried updating one and it did nothing.

**Comment by bradatkins** [comment]
Cancel the payment and add a new one?

**Comment by ali206** [comment]
I don't understand how re-adding would correct the conversion?

the payments posted correctly as you can see below but the conversion is the problem. 

If I manually added back the payments how would the DB know to convert them?

![image](https://cloud.githubusercontent.com/assets/8440903/14113624/c4bf442c-f5a1-11e5-97c3-f27b59d6344d.png)

**Comment by bradatkins** [comment]
Oh duh. Sorry. I'll fix it. What are the correct values?

**Comment by ali206** [comment]
Correct value here is $293.11 USD for her $400 CAD charge (which also doesn't match up with your xchg rate? or is that b/c we're paying $25 on a foreign charge being processed?)

Not sure what the correct March payment value is

**Comment by ali206** [comment]
Correct March USD amount should be i think $2,293.05 USD even though $2,252.50 settled in our account ( i just sent an email about this with McGregor as an ex)

**Comment by bradatkins** [comment]
OK check now. If it's not correct please let me know the values

**Comment by ali206** [comment]
CAD amount on CAD invoice for Nov should show as $400 CAD.  Amt in USD on USD I corrected. 

March charge in CAD should show as $3048 CAD:  USD amt on USD invoice I corrected.
![image](https://cloud.githubusercontent.com/assets/8440903/15430989/cf7fb5e8-1e75-11e6-9f65-c3efea1775de.png)

**Comment by ali206** [comment]
Can you fix this when you get a chance?
Charge from 11/30 should be showing as $400 CAD on CAD invoice

Charge on 3/31 should be $3,048 CAD on CAD invoice
