### ISSUE TITLE
New Look - Initial Testing - Double Express Checkout - expands everything (Ronen)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#743]
Hi Brad,

I was running a test with 2 PAX and when i selected express checkout and then i checked same as PAX 1 and then express checkout again, everything expanded:

![image](https://cloud.githubusercontent.com/assets/10079829/12517939/6c05c662-c103-11e5-844a-327e67b08e8d.png)

**Comment by bradatkins** [comment]
Fixed.

**Comment by ronenreinheimer** [comment]
thank you for looking into this issue Brad. The only things i still see are the ROOMATE REQUEST and the pre / post stay options:

![image](https://cloud.githubusercontent.com/assets/10079829/12588233/aa49c7dc-c425-11e5-912b-69bb58fb08e8.png)

**Comment by bradatkins** [comment]
Fixed.

**Comment by ronenreinheimer** [comment]
Hi Brad,

I ran a test and it worked - however i selected a bag for PAX 1 and it didn't do the same for PAX 2

![image](https://cloud.githubusercontent.com/assets/10079829/12626243/b8f83792-c505-11e5-8c63-76de09629ba8.png)

**Comment by bradatkins** [comment]
Please log a separate issue for this. It's related to the same as previous
passenger functionality and not express checkout.

**Comment by ronenreinheimer** [comment]
understood

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
when i select express checkout with 2 PAX - PAX #1 options are not suppressed.

![image](https://cloud.githubusercontent.com/assets/10079829/12652833/bee0e586-c5ba-11e5-84ed-30d47dd46e98.png)

**Comment by bradatkins** [comment]
Closing, hasn't happened since
