### ISSUE TITLE
415993 - dupe pax for no reason messing up invoice

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#783]
Dear All, 

 Please see below.  Added a pax to an existing record, DB doubled him. 
 I cancelled out the fake pax and DB cancelled both.  
Pricing for the fake pax was wrong too.  Please assist.  Thank you.

![image](https://cloud.githubusercontent.com/assets/8440903/12825147/d98826be-cb42-11e5-8ee2-4abde24430fd.png)

**Comment by ali206** [comment]
Clients are getting antsy, anyway to fix this one today?

**Comment by bradatkins** [comment]
Fixed, sort of...I'm not sure if the second PAX should have any options.

Have a look

**Comment by ali206** [comment]
pax 2 sub-total still isn't showing but is adding in to total costs.

**Comment by bradatkins** [comment]
All good now
