### ISSUE TITLE
None of the search fields are working for ARC TICKETS section

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#87]
and I kind of need this ASAP please if you can.

Thanks!

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
In ARC TICKETS all fields are working except for the tckt Amount box.

Genereating excel report still not working or doing anything and bringing me to a blank page:
![image](https://cloud.githubusercontent.com/assets/8440903/5941244/a849e36a-a6dd-11e4-81c1-4fbd1f8755fe.png)

**Comment by bradatkins** [comment]
Both issues are now resolved

**Comment by ali206** [comment]
Still unable to search by $ amount:

![image](https://cloud.githubusercontent.com/assets/8440903/6667363/e1a3ec56-cbc1-11e4-83fe-8701579ee8d3.png)

**Comment by bradatkins** [comment]
Are we even using this section anymore?
