### ISSUE TITLE
420742 - math wrong

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#873]
subtotal and total trip cost after free amount applied should be $2229 not $5611 or $7627:
![image](https://cloud.githubusercontent.com/assets/8440903/13293586/38925e6c-daee-11e5-9a8d-8a1b63391b26.png)

Balance due should then be $2229 as well

![image](https://cloud.githubusercontent.com/assets/8440903/13293892/9a8cf37e-daef-11e5-8dfe-3c7de76e2f2d.png)

**Comment by bradatkins** [comment]
Fixed. This was the same issue as the other one (the FREE not updating the balance).

**Comment by ali206** [comment]
Ok balance due is correct but now there's no subtotal and the order total is still wrong should be $2,229

![image](https://cloud.githubusercontent.com/assets/8440903/13467933/6bfb7074-e06e-11e5-99c3-cdf58ed0e3f7.png)

**Comment by bradatkins** [comment]
Sub total is added; however, I respectfully disagree that it should be, 2,229, it would make no sense.

Subtotal = 2229
Payment: 5548
Balance Due: 2229?
