### ISSUE TITLE
took payments but invoices are wrong, inaccurate | 421537  (Rinda / Yaritza)

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#893]
![image](https://cloud.githubusercontent.com/assets/10079829/13398304/bec80cee-decb-11e5-8584-3954d29eda7b.png)

**Comment by bradatkins** [comment]
So nothing in this email tells me what the actual incorrect value is?

**Comment by ali206** [comment]
Ok i'm going to go booking by booking b/c this is kind of confusing...

421537 - the invoice sent out in December was mathematically correct:
![image](https://cloud.githubusercontent.com/assets/8440903/13464399/0da8f19a-e05f-11e5-874a-2aacf7306ffd.png)
![image](https://cloud.githubusercontent.com/assets/8440903/13464407/1406be0a-e05f-11e5-8304-ad0392fdb49c.png)

But the balance due email sent out on 2/23 was wrong, applying the $200 discount twice:
![image](https://cloud.githubusercontent.com/assets/8440903/13464449/4b3c9020-e05f-11e5-8512-6705bfadb182.png)

Then yaritza went to make a payment, selected pay in full which was $1,548 at the time and the base price decreased by $100 afterwards for some reason so it looks like we owe them $100.00. 

![image](https://cloud.githubusercontent.com/assets/8440903/13464512/89815c76-e05f-11e5-9aba-2dfea614e5af.png)


and yaritza is not the one that changed the base price of the tour:

![image](https://cloud.githubusercontent.com/assets/8440903/13464501/7d5fc3c4-e05f-11e5-9036-9fd677979fdf.png)

**Comment by ali206** [comment]
421574 - balance due email sent out in Feb. applied discount of $200 twice so was incorrect total due

![image](https://cloud.githubusercontent.com/assets/8440903/13464646/24eb4654-e060-11e5-9090-5e05ffd5701a.png)

Received a payment confirmation email (even though no payment was applied??) showing correct balance due of $1594:
![image](https://cloud.githubusercontent.com/assets/8440903/13464682/4b805b1a-e060-11e5-88d0-2a5a3cd705fb.png)

Current invoice applying $200 discount twice again:
![image](https://cloud.githubusercontent.com/assets/8440903/13464707/6e54bbf4-e060-11e5-998a-115cfcd43102.png)

**Comment by ali206** [comment]
421575 - discount being applied twice again:
![image](https://cloud.githubusercontent.com/assets/8440903/13464750/99e2511e-e060-11e5-9778-7f963d6d3400.png)

**Comment by ronenreinheimer** [comment]
GO ALI

Have a blessed Lenten season,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by bradatkins** [comment]
Fixed

**Comment by ali206** [comment]
This still shows wrong base price:
![image](https://cloud.githubusercontent.com/assets/8440903/18851493/518d4a4c-840a-11e6-9f77-52094f7acd4e.png)

Discount no longer showing ( I will re-add) and base price $100 cheaper...should be $3849 for a PIF invoice
![image](https://cloud.githubusercontent.com/assets/8440903/18851619/ca2a8e10-840a-11e6-8842-3723b5be348f.png)
